services:
  - type: web
    name: flarum
    env: docker
    plan: starter
    image: mondedie/flarum:stable
    env_vars:
      FLARUM_ENV_FILE: ${FLARUM_ENV_FILE}  # Path to your environment file if necessary
      DB_HOST: ${DB_HOST}  # Set these according to the details provided by Render
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "80:8888"
