services:
  - type: web
    name: flarum
    env: docker
    plan: starter  # Choose an appropriate plan based on your needs
    image: mondedie/flarum:stable  # Specify the Docker image directly
    build_command: ""  # Not needed since using a pre-built image
    start_command: ""  # Not needed since using a pre-built image
    env_vars:
      FLARUM_ENV_FILE: ${FLARUM_ENV_FILE}  # Define any required environment variables
      # Add any other environment variables needed for Flarum
    ports:
      - "80:8888"